### PR TITLE
More pleasant styles + small fixes for paragraphs

### PR DESCRIPTION
**Pull request by believer-ufa**
**Before:**

**After:**

### CODE REVIEW

**Comment by believer-ufa** [comment]
And more pleasant nested details:

**Comment by sijad** [comment]
@believer-ufa thanks again. I'm not an css expert but I'm not sure hiding `<br>` is a good idea, also removing margin from `<p>` can make content look different from post itself.

**Comment by believer-ufa** [comment]
Yes, this rules remove margins for next two paragraphs after spoiler, and it can make small effect on other content after spoiler. But it's a very light change, and in most cases forum visitors not see the problems.

But. If you wish, skip this rules) But in situations where you create few details consecutive, forum creates long spaces between it.

**Comment by sijad** [comment]
Merged with few changes in commit message and code, I still thinks it's not a good idea to hide break lines with css, lets hope this problem fixes in next Flarum releases. thanks again

**Pull request closed without merging**
